import { readFileSync } from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'
import { summarise } from '../src/cli'
import { DEFAULT_CONFIG, parseConfig } from '../src/config'
import { evaluateRatchet, groupScores, planBaselineUpdate } from '../src/ratchet'
import type { FunctionScore, Measurement } from '../src/types'
import { observe } from './helpers/parity'

// parity-golden.json was generated by the copied code, before any config existed.
const golden: unknown = JSON.parse(readFileSync(path.join(__dirname, 'fixtures/parity-golden.json'), 'utf8'))

describe('default configuration reproduces the copied outputs byte for byte', () => {
  it('with no config', () => {
    expect(observe()).toEqual(golden)
  })

  it('with the default config object', () => {
    expect(observe({ config: DEFAULT_CONFIG }, DEFAULT_CONFIG.threshold)).toEqual(golden)
  })

  it('with a config parsed from an empty file', () => {
    const config = parseConfig('{}')
    expect(observe({ config }, config.threshold)).toEqual(golden)
  })

  it('with a config file that spells out every default', () => {
    const config = parseConfig(JSON.stringify(DEFAULT_CONFIG))
    expect(observe({ config }, config.threshold)).toEqual(golden)
  })
})

describe('threshold is threaded through every use', () => {
  const fn = (crap: number): FunctionScore => ({ file: 'src/a.ts', symbol: 's', kind: 'Function', line: 1, cc: 1, cov: 0, covKind: 'stmt', crap })
  const measurement = (...scores: number[]): Measurement => ({ functions: scores.map(fn), unmatched: [], problems: [] })

  it('summarise counts offenders above the threshold', () => {
    expect(summarise(measurement(9, 12, 20)).over5).toBe(3)
    expect(summarise(measurement(9, 12, 20), 10).over5).toBe(2)
    expect(summarise(measurement(9, 12, 20), 10).sumOver5).toBe(32)
  })

  it('evaluateRatchet reports a new offender against the threshold', () => {
    const current = groupScores([fn(9)])
    expect(evaluateRatchet(new Map(), current, 8)).toHaveLength(1)
    expect(evaluateRatchet(new Map(), current, 10)).toHaveLength(0)
  })

  it('planBaselineUpdate freezes only offenders above the threshold', () => {
    const current = groupScores([fn(9), fn(30)])
    expect(planBaselineUpdate(null, current, false).baseline.get('src/a.ts\ts')).toEqual([9, 30])
    expect(planBaselineUpdate(null, current, false, 10).baseline.get('src/a.ts\ts')).toEqual([30])
  })

  it('planBaselineUpdate refuses growth above the threshold only', () => {
    const existing = groupScores([fn(50)])
    expect(planBaselineUpdate(existing, groupScores([fn(50), fn(9)]), false).refused).toHaveLength(1)
    expect(planBaselineUpdate(existing, groupScores([fn(50), fn(9)]), false, 10).refused).toHaveLength(0)
  })

  it('a whole run at a higher threshold freezes and counts nothing below it', () => {
    const raised = { ...DEFAULT_CONFIG, threshold: 200 }
    const out = observe({ config: raised }, raised.threshold) as Record<string, { logs: string[]; baselineTsv?: string }>
    expect(out.measureAccept.logs).toEqual(['CRAP measure: functions=10 over5=0 sumOver5=0.0 unmatched=0'])
    expect(out.baseline.baselineTsv).not.toContain('src/hot.ts')
  })
})

describe('ratchet messages carry the configured threshold', () => {
  const fn = (crap: number): FunctionScore => ({ file: 'src/a.ts', symbol: 's', kind: 'Function', line: 1, cc: 1, cov: 0, covKind: 'stmt', crap })

  it('a new offender names the threshold it exceeded', () => {
    const [v] = evaluateRatchet(new Map(), groupScores([fn(25)]), 20)
    expect(v.message).toBe('scores 25.0, above the threshold of 20, and is not in crap/baseline.tsv')
  })

  it('a stale row names the threshold it fell to or below', () => {
    const [v] = evaluateRatchet(groupScores([fn(90)]), groupScores([fn(15)]), 20)
    expect(v.message).toBe('was frozen at 90.0 but now scores 15.0, at or below the threshold of 20')
  })

  it('a refused baseline growth names the threshold', () => {
    const { refused } = planBaselineUpdate(groupScores([]), groupScores([fn(25)]), false, 20)
    expect(refused[0].message).toBe('scores 25.0, above the threshold of 20, and is not in crap/baseline.tsv')
  })
})
